### ISSUE TITLE
Hello sir this package doesn't work at flutterflow when i try web publishing

### ISSUE THREAD

**Issue by JanbertCampos** [GabrielDimaa/qrcode_reader_web#3]
hello sir i try your package in flutterflow but it doesn't work as you can see in the console it had a bunch of errors =)
![image](https://github.com/GabrielDimaa/qrcode_reader_web/assets/33562306/b86640b2-dc3e-471e-ae48-87717edb77c6)

**Comment by GabrielDimaa** [comment]
Hello, could you tell me which version of Flutter you tested?

Also, did you add <script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script> in index.html?
