### ISSUE TITLE
TypeError: dart.global.jsQR is not a function

### ISSUE THREAD

**Issue by roberto-donext** [GabrielDimaa/qrcode_reader_web#4]
When I launch the pluging, I constantly read this in the log console:
TypeError: dart.global.jsQR is not a function

packages/qrcode_reader_web/src/libraries/jsqr_library.dart 102:12        [_captureCode]
packages/qrcode_reader_web/src/libraries/jsqr_library.dart 48:50         <fn>
dart-sdk/lib/async/stream.dart 497:32                                    sendEvent
dart-sdk/lib/_internal/js_dev_runtime/private/isolate_helper.dart 80:17  <fn>
TypeError: dart.global.jsQR is not a function
packages/qrcode_reader_web/src/libraries/jsqr_library.dart 102:12        [_captureCode]
Thanks

**Comment by GabrielDimaa** [comment]
Hello, could you tell me which version of Flutter you tested?

Also, did you add `<script src="https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.min.js"></script>`  in index.html?
